version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - node --version
      - npm --version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Logging in to Docker...
      - echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin
      - IMAGE_NAME=nextjs-better-auth-cognito-dev
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL --build-arg MONGODB_URI=$MONGODB_URI -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "REPOSITORY_URI=$REPOSITORY_URI" > deploy.env
      - echo "IMAGE_TAG=$IMAGE_TAG" >> deploy.env
      - echo "IMAGE_NAME=$IMAGE_NAME" >> deploy.env
      - echo "AWS_REGION=$AWS_REGION" >> deploy.env
artifacts:
  files:
    - deploy.env
